export const data = [
  { id: 1, tagName: "웹 취약점 공격", category: 3 },
  { id: 2, tagName: "포렌식", category: 4 },
  { id: 3, tagName: "시스템 취약점 공격", category: 3 },
  { id: 4, tagName: "시큐어 코딩", category: 1 },
  { id: 5, tagName: "정보 보안 교육", category: 2 },
  { id: 6, tagName: "랜섬웨어", category: 4 },
  { id: 7, tagName: "악성코드 분석", category: 4 },
  { id: 8, tagName: "패킷 분석", category: 1 },
  { id: 9, tagName: "솔루션 정책 점검", category: 2 },
  { id: 10, tagName: "정보보안 법률", category: 2 },
  { id: 11, tagName: "보안 프로그램", category: 1 },
  { id: 12, tagName: "소스코드 진단", category: 3 },
  { id: 13, tagName: "APT 공격", category: 1 },
  { id: 14, tagName: "개인정보 처리 점검", category: 2 },
  { id: 15, tagName: "보안 솔루션", category: 1 },
  { id: 16, tagName: "DDoS 공격", category: 1 },
  { id: 17, tagName: "관리 체계 점검", category: 2 },
  { id: 18, tagName: "로그 분석", category: 1 },
  { id: 19, tagName: "AD 서버 관리자 계정 탈취", category: 4 },
]